CREATE DATABASE DB_FERAS_REDACAO;

CREATE TABLE TAB_ALUNO
(
	COD_ALUNO	INT		IDENTITY(0,1)	PRIMARY KEY		NOT NULL,
	NOME		VARCHAR(255),
	REDACAO		TEXT	NOT NULL,
	FACULDADE	VARCHAR(30)		NOT NULL,
	EMAIL		VARCHAR(30)		NOT NULL,
	PAGAMENTO	TEXT	NOT NULL,
	TELEFONE	TINYINT	NOT NULL
);

CREATE TABLE TAB_PROFESSORES
(
	COD_PROF	INT		IDENTITY(0,1)	PRIMARY KEY		NOT NULL,
	CORRECAO	TEXT	NOT NULL,
	REDACAO		TEXT	NOT NULL,
	NOME		VARCHAR(255)	NOT NULL,
	TELEFONE	TINYINT	NOT NULL
);

CREATE TABLE TAB_CHAT
(
	COD_CHAT	INT		IDENTITY(0,1)	PRIMARY KEY		NOT NULL,
	COD_ALUNO	INT		NOT NULL,
	COD_PROF	INT		NOT NULL,
	HISTORICO	TEXT	NOT NULL,
	CONSTRAINT	FK_COD_ALUNO	FOREIGN KEY(COD_ALUNO)	REFERENCES TAB_ALUNO(COD_ALUNO),
	CONSTRAINT  FK_COD_PROF		FOREIGN KEY(COD_PROF)	REFERENCES TAB_PROFESSORES(COD_PROF)
);

CREATE TABLE TAB_SISTEMA
(
	DICAS		TEXT	NOT NULL,
	COD_ALUNO	INT		NOT NULL,
	COD_PROF	INT		NOT NULL,
	ARTIGOS		TEXT	NOT NULL,
	CONSTRAINT	FK_COD_ALUNOD	FOREIGN KEY(COD_ALUNO)
	REFERENCES	TAB_ALUNO(COD_ALUNO),
	CONSTRAINT	FK_COD_PROFD		FOREIGN KEY(COD_PROF)
	REFERENCES	TAB_PROFESSORES(COD_PROF)
);